// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.gl.edfstubs;

public final class EmployeeServiceOuterClass {
  private EmployeeServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EmployeeService.proto\022\ncom.gl.edf\032\016Emp" +
      "loyee.proto\032\016Response.proto\032\033google/prot" +
      "obuf/empty.proto2\273\002\n\017EmployeeService\022=\n\014" +
      "allemployees\022\026.google.protobuf.Empty\032\025.c" +
      "om.gl.edf.Employees\022:\n\014editemployee\022\024.co" +
      "m.gl.edf.Employee\032\024.com.gl.edf.Response\022" +
      "9\n\013addemployee\022\024.com.gl.edf.Employee\032\024.c" +
      "om.gl.edf.Response\022<\n\016deleteemployee\022\024.c" +
      "om.gl.edf.Employee\032\024.com.gl.edf.Response" +
      "\0224\n\004test\022\026.google.protobuf.Empty\032\024.com.g" +
      "l.edf.ResponseB\021\n\017com.gl.edfstubsb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gl.edfstubs.EmployeeOuterClass.getDescriptor(),
          com.gl.edfstubs.ResponseOuterClass.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    com.gl.edfstubs.EmployeeOuterClass.getDescriptor();
    com.gl.edfstubs.ResponseOuterClass.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
