// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.gl.edfstubs;

public final class EmployeeService {
  private EmployeeService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EmployeeService.proto\032\016Employee.proto\032" +
      "\016Response.proto2\250\001\n\017EmployeeDetails\022\"\n\014a" +
      "llemployees\022\006.Empty\032\n.Employees\022$\n\014edite" +
      "mployee\022\t.Employee\032\t.Response\022#\n\013addempl" +
      "oyee\022\t.Employee\032\t.Response\022&\n\016deleteempl" +
      "oyee\022\t.Employee\032\t.ResponseB\021\n\017com.gl.edf" +
      "stubsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gl.edfstubs.EmployeeOuterClass.getDescriptor(),
          com.gl.edfstubs.ResponseOuterClass.getDescriptor(),
        }, assigner);
    com.gl.edfstubs.EmployeeOuterClass.getDescriptor();
    com.gl.edfstubs.ResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
