// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.gl.edfstubs;

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 employeeid = 1;</code>
     */
    long getEmployeeid();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string project = 3;</code>
     */
    java.lang.String getProject();
    /**
     * <code>string project = 3;</code>
     */
    com.google.protobuf.ByteString
        getProjectBytes();

    /**
     * <code>repeated string skills = 4;</code>
     */
    java.util.List<java.lang.String>
        getSkillsList();
    /**
     * <code>repeated string skills = 4;</code>
     */
    int getSkillsCount();
    /**
     * <code>repeated string skills = 4;</code>
     */
    java.lang.String getSkills(int index);
    /**
     * <code>repeated string skills = 4;</code>
     */
    com.google.protobuf.ByteString
        getSkillsBytes(int index);

    /**
     * <code>int64 phonenumber = 5;</code>
     */
    long getPhonenumber();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public  static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      employeeid_ = 0L;
      name_ = "";
      project_ = "";
      skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      phonenumber_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              employeeid_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              project_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                skills_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              skills_.add(s);
              break;
            }
            case 40: {

              phonenumber_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          skills_ = skills_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gl.edfstubs.EmployeeOuterClass.Employee.class, com.gl.edfstubs.EmployeeOuterClass.Employee.Builder.class);
    }

    private int bitField0_;
    public static final int EMPLOYEEID_FIELD_NUMBER = 1;
    private long employeeid_;
    /**
     * <code>int64 employeeid = 1;</code>
     */
    public long getEmployeeid() {
      return employeeid_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECT_FIELD_NUMBER = 3;
    private volatile java.lang.Object project_;
    /**
     * <code>string project = 3;</code>
     */
    public java.lang.String getProject() {
      java.lang.Object ref = project_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        project_ = s;
        return s;
      }
    }
    /**
     * <code>string project = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProjectBytes() {
      java.lang.Object ref = project_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        project_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKILLS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList skills_;
    /**
     * <code>repeated string skills = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSkillsList() {
      return skills_;
    }
    /**
     * <code>repeated string skills = 4;</code>
     */
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated string skills = 4;</code>
     */
    public java.lang.String getSkills(int index) {
      return skills_.get(index);
    }
    /**
     * <code>repeated string skills = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSkillsBytes(int index) {
      return skills_.getByteString(index);
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 5;
    private long phonenumber_;
    /**
     * <code>int64 phonenumber = 5;</code>
     */
    public long getPhonenumber() {
      return phonenumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (employeeid_ != 0L) {
        output.writeInt64(1, employeeid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getProjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, project_);
      }
      for (int i = 0; i < skills_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, skills_.getRaw(i));
      }
      if (phonenumber_ != 0L) {
        output.writeInt64(5, phonenumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (employeeid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, employeeid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getProjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, project_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < skills_.size(); i++) {
          dataSize += computeStringSizeNoTag(skills_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSkillsList().size();
      }
      if (phonenumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, phonenumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gl.edfstubs.EmployeeOuterClass.Employee)) {
        return super.equals(obj);
      }
      com.gl.edfstubs.EmployeeOuterClass.Employee other = (com.gl.edfstubs.EmployeeOuterClass.Employee) obj;

      boolean result = true;
      result = result && (getEmployeeid()
          == other.getEmployeeid());
      result = result && getName()
          .equals(other.getName());
      result = result && getProject()
          .equals(other.getProject());
      result = result && getSkillsList()
          .equals(other.getSkillsList());
      result = result && (getPhonenumber()
          == other.getPhonenumber());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EMPLOYEEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEmployeeid());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PROJECT_FIELD_NUMBER;
      hash = (53 * hash) + getProject().hashCode();
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + getSkillsList().hashCode();
      }
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPhonenumber());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gl.edfstubs.EmployeeOuterClass.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gl.edfstubs.EmployeeOuterClass.Employee.class, com.gl.edfstubs.EmployeeOuterClass.Employee.Builder.class);
      }

      // Construct using com.gl.edfstubs.EmployeeOuterClass.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        employeeid_ = 0L;

        name_ = "";

        project_ = "";

        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        phonenumber_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Employee getDefaultInstanceForType() {
        return com.gl.edfstubs.EmployeeOuterClass.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Employee build() {
        com.gl.edfstubs.EmployeeOuterClass.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Employee buildPartial() {
        com.gl.edfstubs.EmployeeOuterClass.Employee result = new com.gl.edfstubs.EmployeeOuterClass.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.employeeid_ = employeeid_;
        result.name_ = name_;
        result.project_ = project_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          skills_ = skills_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.skills_ = skills_;
        result.phonenumber_ = phonenumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gl.edfstubs.EmployeeOuterClass.Employee) {
          return mergeFrom((com.gl.edfstubs.EmployeeOuterClass.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gl.edfstubs.EmployeeOuterClass.Employee other) {
        if (other == com.gl.edfstubs.EmployeeOuterClass.Employee.getDefaultInstance()) return this;
        if (other.getEmployeeid() != 0L) {
          setEmployeeid(other.getEmployeeid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getProject().isEmpty()) {
          project_ = other.project_;
          onChanged();
        }
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
        if (other.getPhonenumber() != 0L) {
          setPhonenumber(other.getPhonenumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gl.edfstubs.EmployeeOuterClass.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gl.edfstubs.EmployeeOuterClass.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long employeeid_ ;
      /**
       * <code>int64 employeeid = 1;</code>
       */
      public long getEmployeeid() {
        return employeeid_;
      }
      /**
       * <code>int64 employeeid = 1;</code>
       */
      public Builder setEmployeeid(long value) {
        
        employeeid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 employeeid = 1;</code>
       */
      public Builder clearEmployeeid() {
        
        employeeid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object project_ = "";
      /**
       * <code>string project = 3;</code>
       */
      public java.lang.String getProject() {
        java.lang.Object ref = project_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          project_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string project = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProjectBytes() {
        java.lang.Object ref = project_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          project_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string project = 3;</code>
       */
      public Builder setProject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        project_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string project = 3;</code>
       */
      public Builder clearProject() {
        
        project_ = getDefaultInstance().getProject();
        onChanged();
        return this;
      }
      /**
       * <code>string project = 3;</code>
       */
      public Builder setProjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        project_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          skills_ = new com.google.protobuf.LazyStringArrayList(skills_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSkillsList() {
        return skills_.getUnmodifiableView();
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public int getSkillsCount() {
        return skills_.size();
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public java.lang.String getSkills(int index) {
        return skills_.get(index);
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSkillsBytes(int index) {
        return skills_.getByteString(index);
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public Builder setSkills(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public Builder addSkills(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public Builder addAllSkills(
          java.lang.Iterable<java.lang.String> values) {
        ensureSkillsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skills_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public Builder clearSkills() {
        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       */
      public Builder addSkillsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }

      private long phonenumber_ ;
      /**
       * <code>int64 phonenumber = 5;</code>
       */
      public long getPhonenumber() {
        return phonenumber_;
      }
      /**
       * <code>int64 phonenumber = 5;</code>
       */
      public Builder setPhonenumber(long value) {
        
        phonenumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 phonenumber = 5;</code>
       */
      public Builder clearPhonenumber() {
        
        phonenumber_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final com.gl.edfstubs.EmployeeOuterClass.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gl.edfstubs.EmployeeOuterClass.Employee();
    }

    public static com.gl.edfstubs.EmployeeOuterClass.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gl.edfstubs.EmployeeOuterClass.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmployeesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employees)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    java.util.List<com.gl.edfstubs.EmployeeOuterClass.Employee> 
        getEmployeeList();
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    com.gl.edfstubs.EmployeeOuterClass.Employee getEmployee(int index);
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    int getEmployeeCount();
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    java.util.List<? extends com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder> 
        getEmployeeOrBuilderList();
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder getEmployeeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Employees}
   */
  public  static final class Employees extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employees)
      EmployeesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employees.newBuilder() to construct.
    private Employees(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employees() {
      employee_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employees(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                employee_ = new java.util.ArrayList<com.gl.edfstubs.EmployeeOuterClass.Employee>();
                mutable_bitField0_ |= 0x00000001;
              }
              employee_.add(
                  input.readMessage(com.gl.edfstubs.EmployeeOuterClass.Employee.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          employee_ = java.util.Collections.unmodifiableList(employee_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employees_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employees_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gl.edfstubs.EmployeeOuterClass.Employees.class, com.gl.edfstubs.EmployeeOuterClass.Employees.Builder.class);
    }

    public static final int EMPLOYEE_FIELD_NUMBER = 1;
    private java.util.List<com.gl.edfstubs.EmployeeOuterClass.Employee> employee_;
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    public java.util.List<com.gl.edfstubs.EmployeeOuterClass.Employee> getEmployeeList() {
      return employee_;
    }
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    public java.util.List<? extends com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder> 
        getEmployeeOrBuilderList() {
      return employee_;
    }
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    public int getEmployeeCount() {
      return employee_.size();
    }
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    public com.gl.edfstubs.EmployeeOuterClass.Employee getEmployee(int index) {
      return employee_.get(index);
    }
    /**
     * <code>repeated .Employee employee = 1;</code>
     */
    public com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder getEmployeeOrBuilder(
        int index) {
      return employee_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < employee_.size(); i++) {
        output.writeMessage(1, employee_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < employee_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, employee_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gl.edfstubs.EmployeeOuterClass.Employees)) {
        return super.equals(obj);
      }
      com.gl.edfstubs.EmployeeOuterClass.Employees other = (com.gl.edfstubs.EmployeeOuterClass.Employees) obj;

      boolean result = true;
      result = result && getEmployeeList()
          .equals(other.getEmployeeList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEmployeeCount() > 0) {
        hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
        hash = (53 * hash) + getEmployeeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Employees parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gl.edfstubs.EmployeeOuterClass.Employees prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employees}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employees)
        com.gl.edfstubs.EmployeeOuterClass.EmployeesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employees_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employees_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gl.edfstubs.EmployeeOuterClass.Employees.class, com.gl.edfstubs.EmployeeOuterClass.Employees.Builder.class);
      }

      // Construct using com.gl.edfstubs.EmployeeOuterClass.Employees.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEmployeeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (employeeBuilder_ == null) {
          employee_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          employeeBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Employees_descriptor;
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Employees getDefaultInstanceForType() {
        return com.gl.edfstubs.EmployeeOuterClass.Employees.getDefaultInstance();
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Employees build() {
        com.gl.edfstubs.EmployeeOuterClass.Employees result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Employees buildPartial() {
        com.gl.edfstubs.EmployeeOuterClass.Employees result = new com.gl.edfstubs.EmployeeOuterClass.Employees(this);
        int from_bitField0_ = bitField0_;
        if (employeeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            employee_ = java.util.Collections.unmodifiableList(employee_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.employee_ = employee_;
        } else {
          result.employee_ = employeeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gl.edfstubs.EmployeeOuterClass.Employees) {
          return mergeFrom((com.gl.edfstubs.EmployeeOuterClass.Employees)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gl.edfstubs.EmployeeOuterClass.Employees other) {
        if (other == com.gl.edfstubs.EmployeeOuterClass.Employees.getDefaultInstance()) return this;
        if (employeeBuilder_ == null) {
          if (!other.employee_.isEmpty()) {
            if (employee_.isEmpty()) {
              employee_ = other.employee_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEmployeeIsMutable();
              employee_.addAll(other.employee_);
            }
            onChanged();
          }
        } else {
          if (!other.employee_.isEmpty()) {
            if (employeeBuilder_.isEmpty()) {
              employeeBuilder_.dispose();
              employeeBuilder_ = null;
              employee_ = other.employee_;
              bitField0_ = (bitField0_ & ~0x00000001);
              employeeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEmployeeFieldBuilder() : null;
            } else {
              employeeBuilder_.addAllMessages(other.employee_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gl.edfstubs.EmployeeOuterClass.Employees parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gl.edfstubs.EmployeeOuterClass.Employees) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.gl.edfstubs.EmployeeOuterClass.Employee> employee_ =
        java.util.Collections.emptyList();
      private void ensureEmployeeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          employee_ = new java.util.ArrayList<com.gl.edfstubs.EmployeeOuterClass.Employee>(employee_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gl.edfstubs.EmployeeOuterClass.Employee, com.gl.edfstubs.EmployeeOuterClass.Employee.Builder, com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder> employeeBuilder_;

      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public java.util.List<com.gl.edfstubs.EmployeeOuterClass.Employee> getEmployeeList() {
        if (employeeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(employee_);
        } else {
          return employeeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public int getEmployeeCount() {
        if (employeeBuilder_ == null) {
          return employee_.size();
        } else {
          return employeeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public com.gl.edfstubs.EmployeeOuterClass.Employee getEmployee(int index) {
        if (employeeBuilder_ == null) {
          return employee_.get(index);
        } else {
          return employeeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder setEmployee(
          int index, com.gl.edfstubs.EmployeeOuterClass.Employee value) {
        if (employeeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeeIsMutable();
          employee_.set(index, value);
          onChanged();
        } else {
          employeeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder setEmployee(
          int index, com.gl.edfstubs.EmployeeOuterClass.Employee.Builder builderForValue) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          employee_.set(index, builderForValue.build());
          onChanged();
        } else {
          employeeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder addEmployee(com.gl.edfstubs.EmployeeOuterClass.Employee value) {
        if (employeeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeeIsMutable();
          employee_.add(value);
          onChanged();
        } else {
          employeeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder addEmployee(
          int index, com.gl.edfstubs.EmployeeOuterClass.Employee value) {
        if (employeeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeeIsMutable();
          employee_.add(index, value);
          onChanged();
        } else {
          employeeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder addEmployee(
          com.gl.edfstubs.EmployeeOuterClass.Employee.Builder builderForValue) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          employee_.add(builderForValue.build());
          onChanged();
        } else {
          employeeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder addEmployee(
          int index, com.gl.edfstubs.EmployeeOuterClass.Employee.Builder builderForValue) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          employee_.add(index, builderForValue.build());
          onChanged();
        } else {
          employeeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder addAllEmployee(
          java.lang.Iterable<? extends com.gl.edfstubs.EmployeeOuterClass.Employee> values) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, employee_);
          onChanged();
        } else {
          employeeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder clearEmployee() {
        if (employeeBuilder_ == null) {
          employee_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          employeeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public Builder removeEmployee(int index) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          employee_.remove(index);
          onChanged();
        } else {
          employeeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public com.gl.edfstubs.EmployeeOuterClass.Employee.Builder getEmployeeBuilder(
          int index) {
        return getEmployeeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder getEmployeeOrBuilder(
          int index) {
        if (employeeBuilder_ == null) {
          return employee_.get(index);  } else {
          return employeeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public java.util.List<? extends com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder> 
           getEmployeeOrBuilderList() {
        if (employeeBuilder_ != null) {
          return employeeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(employee_);
        }
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public com.gl.edfstubs.EmployeeOuterClass.Employee.Builder addEmployeeBuilder() {
        return getEmployeeFieldBuilder().addBuilder(
            com.gl.edfstubs.EmployeeOuterClass.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public com.gl.edfstubs.EmployeeOuterClass.Employee.Builder addEmployeeBuilder(
          int index) {
        return getEmployeeFieldBuilder().addBuilder(
            index, com.gl.edfstubs.EmployeeOuterClass.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employee = 1;</code>
       */
      public java.util.List<com.gl.edfstubs.EmployeeOuterClass.Employee.Builder> 
           getEmployeeBuilderList() {
        return getEmployeeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gl.edfstubs.EmployeeOuterClass.Employee, com.gl.edfstubs.EmployeeOuterClass.Employee.Builder, com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder> 
          getEmployeeFieldBuilder() {
        if (employeeBuilder_ == null) {
          employeeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gl.edfstubs.EmployeeOuterClass.Employee, com.gl.edfstubs.EmployeeOuterClass.Employee.Builder, com.gl.edfstubs.EmployeeOuterClass.EmployeeOrBuilder>(
                  employee_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          employee_ = null;
        }
        return employeeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employees)
    }

    // @@protoc_insertion_point(class_scope:Employees)
    private static final com.gl.edfstubs.EmployeeOuterClass.Employees DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gl.edfstubs.EmployeeOuterClass.Employees();
    }

    public static com.gl.edfstubs.EmployeeOuterClass.Employees getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employees>
        PARSER = new com.google.protobuf.AbstractParser<Employees>() {
      @java.lang.Override
      public Employees parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employees(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employees> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employees> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gl.edfstubs.EmployeeOuterClass.Employees getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gl.edfstubs.EmployeeOuterClass.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gl.edfstubs.EmployeeOuterClass.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gl.edfstubs.EmployeeOuterClass.Empty.class, com.gl.edfstubs.EmployeeOuterClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gl.edfstubs.EmployeeOuterClass.Empty)) {
        return super.equals(obj);
      }
      com.gl.edfstubs.EmployeeOuterClass.Empty other = (com.gl.edfstubs.EmployeeOuterClass.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gl.edfstubs.EmployeeOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        com.gl.edfstubs.EmployeeOuterClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gl.edfstubs.EmployeeOuterClass.Empty.class, com.gl.edfstubs.EmployeeOuterClass.Empty.Builder.class);
      }

      // Construct using com.gl.edfstubs.EmployeeOuterClass.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Empty getDefaultInstanceForType() {
        return com.gl.edfstubs.EmployeeOuterClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Empty build() {
        com.gl.edfstubs.EmployeeOuterClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Empty buildPartial() {
        com.gl.edfstubs.EmployeeOuterClass.Empty result = new com.gl.edfstubs.EmployeeOuterClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gl.edfstubs.EmployeeOuterClass.Empty) {
          return mergeFrom((com.gl.edfstubs.EmployeeOuterClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gl.edfstubs.EmployeeOuterClass.Empty other) {
        if (other == com.gl.edfstubs.EmployeeOuterClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gl.edfstubs.EmployeeOuterClass.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gl.edfstubs.EmployeeOuterClass.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final com.gl.edfstubs.EmployeeOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gl.edfstubs.EmployeeOuterClass.Empty();
    }

    public static com.gl.edfstubs.EmployeeOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gl.edfstubs.EmployeeOuterClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responsemessage = 1;</code>
     */
    java.lang.String getResponsemessage();
    /**
     * <code>string responsemessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponsemessageBytes();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      responsemessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responsemessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gl.edfstubs.EmployeeOuterClass.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gl.edfstubs.EmployeeOuterClass.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gl.edfstubs.EmployeeOuterClass.Response.class, com.gl.edfstubs.EmployeeOuterClass.Response.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responsemessage_;
    /**
     * <code>string responsemessage = 1;</code>
     */
    public java.lang.String getResponsemessage() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responsemessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responsemessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponsemessageBytes() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responsemessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponsemessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responsemessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponsemessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responsemessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gl.edfstubs.EmployeeOuterClass.Response)) {
        return super.equals(obj);
      }
      com.gl.edfstubs.EmployeeOuterClass.Response other = (com.gl.edfstubs.EmployeeOuterClass.Response) obj;

      boolean result = true;
      result = result && getResponsemessage()
          .equals(other.getResponsemessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponsemessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gl.edfstubs.EmployeeOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gl.edfstubs.EmployeeOuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.gl.edfstubs.EmployeeOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gl.edfstubs.EmployeeOuterClass.Response.class, com.gl.edfstubs.EmployeeOuterClass.Response.Builder.class);
      }

      // Construct using com.gl.edfstubs.EmployeeOuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responsemessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gl.edfstubs.EmployeeOuterClass.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Response getDefaultInstanceForType() {
        return com.gl.edfstubs.EmployeeOuterClass.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Response build() {
        com.gl.edfstubs.EmployeeOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gl.edfstubs.EmployeeOuterClass.Response buildPartial() {
        com.gl.edfstubs.EmployeeOuterClass.Response result = new com.gl.edfstubs.EmployeeOuterClass.Response(this);
        result.responsemessage_ = responsemessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gl.edfstubs.EmployeeOuterClass.Response) {
          return mergeFrom((com.gl.edfstubs.EmployeeOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gl.edfstubs.EmployeeOuterClass.Response other) {
        if (other == com.gl.edfstubs.EmployeeOuterClass.Response.getDefaultInstance()) return this;
        if (!other.getResponsemessage().isEmpty()) {
          responsemessage_ = other.responsemessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gl.edfstubs.EmployeeOuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gl.edfstubs.EmployeeOuterClass.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responsemessage_ = "";
      /**
       * <code>string responsemessage = 1;</code>
       */
      public java.lang.String getResponsemessage() {
        java.lang.Object ref = responsemessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responsemessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responsemessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponsemessageBytes() {
        java.lang.Object ref = responsemessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responsemessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responsemessage = 1;</code>
       */
      public Builder setResponsemessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responsemessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responsemessage = 1;</code>
       */
      public Builder clearResponsemessage() {
        
        responsemessage_ = getDefaultInstance().getResponsemessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responsemessage = 1;</code>
       */
      public Builder setResponsemessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responsemessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.gl.edfstubs.EmployeeOuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gl.edfstubs.EmployeeOuterClass.Response();
    }

    public static com.gl.edfstubs.EmployeeOuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gl.edfstubs.EmployeeOuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employees_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employees_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Employee.proto\"b\n\010Employee\022\022\n\nemployee" +
      "id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\017\n\007project\030\003 \001(\t\022" +
      "\016\n\006skills\030\004 \003(\t\022\023\n\013phonenumber\030\005 \001(\003\"(\n\t" +
      "Employees\022\033\n\010employee\030\001 \003(\0132\t.Employee\"\007" +
      "\n\005Empty\"#\n\010Response\022\027\n\017responsemessage\030\001" +
      " \001(\t2\200\001\n\017EmployeeDetails\022\"\n\014allemployees" +
      "\022\006.Empty\032\n.Employees\022$\n\014editemployee\022\t.E" +
      "mployee\032\t.Response\022#\n\013addemployee\022\t.Empl" +
      "oyee\032\t.ResponseB\021\n\017com.gl.edfstubsb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Employeeid", "Name", "Project", "Skills", "Phonenumber", });
    internal_static_Employees_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Employees_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employees_descriptor,
        new java.lang.String[] { "Employee", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Responsemessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
