type: google.api.Service
config_version: 3

name: employeeservice.endpoints.ageless-courier-273610.cloud.goog

title: EmployeeService API
apis:
- name: com.gl.edfstubs.EmployeeService

http:
  rules:
   - selector: com.gl.edfstubs.EmployeeService.test
     get: /test
   - selector: com.gl.edfstubs.EmployeeService.allemployees
     get: /allemployees
   - selector: com.gl.edfstubs.EmployeeService.addemployee
     post: /add
     body: Employee
   - selector: com.gl.edfstubs.EmployeeService.deleteemployee
     post: /edit
     body: Employee

     
  